### ISSUE TITLE
Support for patch: protocol

### ISSUE THREAD

**Issue by moughxyz** [lerna-lite/lerna-lite#223]
Thanks for resurrecting Lerna (with workspace: support). The `version` package is indispensable and irreplaceable. Have tried everything and nothing comes close.

I was able to get successfully ported to lerna-lite for the most part, but I had to remove any ["patch:" protocol](https://yarnpkg.com/features/protocols#patch) references to get it to work. Would be awesome for lerna-lite to gain support for this protocol.

**Comment by ghiscoding** [comment]
@moughxyz 
I never used patch before but looking at what @starpTech commented and used in another issue, it seems possible to apply patching without the need of Lerna-Lite to support it itself, he was using this package [patch-package-with-pnpm-support](https://github.com/Tellus/patch-package-with-pnpm-support) and that lib also support Yarn patching, so you might want to give that a try. 

Also like I said earlier, this is outside of my zone of comfort to implement and if it's possible to use external lib to do the patching then that would be much more preferable to keep the lib small. @starpTech, seems have better knowledge, anything else to say?

**Comment by StarpTech** [comment]
Hi, I also didn't use it before. Seems like a very yarn-specific feature. Some adaption is happening in pnpm https://github.com/pnpm/pnpm/pull/4885#issuecomment-1159656056 but it will not introduce a prefix. Honestly, I don't like the fact that lerna has to adopt package manager features. Maybe a more generic solution like lerna hooks can fulfill all those requirements.

**Comment by tunnckoCore** [comment]
@ghiscoding you can add `blank_issues_enabled: false` in `.github/ISSUE_TEMPLATE/config.yml`. I learned that recently too.

**Comment by ghiscoding** [comment]
@tunnckoCore I'm not sure what you mean, could you elaborate, does that help with the original issue? 

At the end of it, I'm more on the side of @StarpTech in the sense that I don't think the lib should support every little feature flavor of all package managers especially if it's only available in 1 package manager. If however someone can find a way and contribute a viable solution that doesn't require too much code change then I'm also very open to that as well.

**Comment by tunnckoCore** [comment]
Nope, it's regarding the skipping of templates only. 😉 Just came back to share it, because found it recently.

As about the issue, i agree with you. Seems like many "protocols" are poping up in the last year.

**Comment by ghiscoding** [comment]
Thanks to @petermetz this is now supported in [v3.7.0](https://github.com/lerna-lite/lerna-lite/releases/tag/v3.7.0) via recent PR #887
