### ISSUE TITLE
Wrong handling of independent mode?

### ISSUE THREAD

**Issue by StarpTech** [lerna-lite/lerna-lite#324]
### Describe the bug

Hi, I'm a bit curious about how the independent mode works. I made a preview and got the following logs:

```
> lerna version --conventional-commits --changelog-include-commits-client-login --create-release github --git-dry-run

lerna-lite notice cli v1.11.1
lerna-lite verb rootPath /home/starptech/repositories/wundergraph/wundergraph
lerna-lite info dry-run> git rev-parse
lerna-lite info versioning independent
lerna-lite verb project packages packages/nextjs packages/sdk packages/protobuf
lerna-lite info dry-run> git rev-list --count --all --max-count=1
lerna-lite verb isAnythingCommitted 1
lerna-lite verb currentBranch main
lerna-lite info dry-run> git show-ref --verify refs/remotes/origin/main
lerna-lite info dry-run> git remote update
lerna-lite info dry-run> git rev-list --left-right --count origin/main...main
lerna-lite verb hasTags filter for tags with '*@*' pattern
lerna-lite verb hasTags true
lerna-lite verb git-describe.sync "*@*" => "@wundergraph/nextjs@0.1.4-1-g9993f9a"
lerna-lite info Looking for changed packages since @wundergraph/nextjs@0.1.4
lerna-lite verb filtered diff packages/nextjs/package.json
lerna-lite verb filtered diff packages/protobuf/package.json
lerna-lite verb filtered diff packages/sdk/package.json
lerna-lite verb updated @wundergraph/nextjs
lerna-lite verb updated @wundergraph/protobuf
lerna-lite verb updated @wundergraph/sdk
lerna-lite info dry-run> git describe --always --long --dirty --first-parent
lerna-lite verb getChangelogConfig using preset "conventional-changelog-conventionalcommits"
lerna-lite verb getChangelogConfig Attempting to resolve preset "conventional-changelog-conventionalcommits"
lerna-lite info getChangelogConfig Successfully resolved preset "conventional-changelog-conventionalcommits"
lerna-lite verb independent increment 0.1.4 by patch - @wundergraph/nextjs
lerna-lite verb independent increment 0.91.2 by patch - @wundergraph/protobuf
lerna-lite verb independent increment 0.98.3 by patch - @wundergraph/sdk

Changes (3 packages):
 - @wundergraph/nextjs: 0.1.4 => 0.1.5
 - @wundergraph/protobuf: 0.91.2 => 0.91.3
 - @wundergraph/sdk: 0.98.3 => 0.98.4
```

Check the line 

```
lerna-lite verb git-describe.sync "*@*" => "@wundergraph/nextjs@0.1.4-1-g9993f9a"
lerna-lite info Looking for changed packages since @wundergraph/nextjs@0.1.4
```

Shouldn't it be checked for each package individually? Why is `@wundergraph/nextjs@0.1.4` the base?

### Reproduction

No

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

```shell
| Executable        | Version |
| ----------------- | ------- |
| `lerna --version` | 1.11.1 |
| `npm --version`   | VERSION |
| `yarn --version`  | VERSION |
| `node --version`  | VERSION |

---
OR simply run `npx lerna info` command and copy+paste the result here
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I'm not really the person to ask for this since I never used it myself, I would suggest to search on the original Lerna project to see if you can answer to your question. I did however add the dry-run option and I think that portion is working as it should feel free to create PR if you find anything

**Comment by StarpTech** [comment]
I'll look into it, but it would be great to have you on board. It sounds a bit odd to have it in core without any interest in making it work.

**Comment by z3dev** [comment]
@StarpTech the existing tags are really important when new versions are decided. You probably already know that, but just for completeness, can you supply the list of tags?
