### ISSUE TITLE
lerna exec fails to call command with arguments in Powershell

### ISSUE THREAD

**Issue by jeffrson** [lerna-lite/lerna-lite#493]
### Describe the bug

`lerna exec -- git clean -ffdx .` says "Unknown arguments f, d, x"

it works with quote, though: `lerna exec -- "git clean -ffdx ."`

### Expectation

Should execute command just like in bash or cmd - quotes are a just a workaround, IMO

I haven't tried Powershell on Linux so far.

### Reproduction

`lerna exec -- git clean -ffdx .`

### Environment Info

@lerna-lite/exec 1.15.1

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
This was implemented originally by Lerna and as per this [comment](https://github.com/lerna/lerna/issues/1965#issuecomment-480817161) for the original maintainer, it seems to be normal in some cases because of what he wrote there. Feel free to submit a PR if you know how to fix this

**Comment by jeffrson** [comment]
While I would have (more or less) expected such shell behaviour with "&&", it's strange to see it with rather regular arguments.

Also, afaict from some short tests, this could be just a strange effect of how cli.js is wrapped (when installing via `npm i -g`) in cmd/ps1/whatever.

So I think, documentation is simple enough and sufficient :-)
