### ISSUE TITLE
Allow to add a suffix to specific packages when publishing

### ISSUE THREAD

**Issue by dreamorosi** [lerna-lite/lerna-lite#638]
### Clear and concise description of the problem

As a developer I want to be able to add a custom suffix to the version of specific packages in my workspace, even when I'm running the workspace with versions aligned.

### Suggested solution

Imagine that I have 3 packages, all are published using the same version (i.e. `v1.9.0`). I now want to add a fourth package (`package-d`) that for a period of time will be in beta, to avoid confusing my users I want the versioning of this package to pick up at the same version number of the others, but with a `-beta` suffix.

When I version the next time (`npx lerna version --conventional-commits --force-publish`), I would like to have a version scheme like this:
```
package-a 1.9.0 -> 1.9.1
package-b 1.9.0 -> 1.9.1
package-c 1.9.0 -> 1.9.1
package-d 1.9.0-beta -> 1.9.1-beta
```

From a config perspective, this could be as simple as providing a new section to the `lerna.json` under `command.version`, that looks like this:
```json
{
  "packages": [
    "package-a",
    "package-b",
    "package-c",
    "package-d",
  ],
  "command": {
    "version": {
      "suffix": {
        "package-d": "-beta"
      }
    }
  }
}
```

Note that the above suggestion is only an example, as long as this type of customization is possible on a per-package basis I wouldn't mind other ways.

### Alternative

Currently I'm relying on a `prepack` custom script (at publish time) that:
- reads the `package.json`
- gets the version
- adds the suffix
- updates the `package.json`

Lerna will reset the changes, so the version is present only in the tarball being published to npm.

This however causes issues when used with the `publish.removePackageFields` feature, which prevents me to using it in the first place - see #637 

### Additional context

I have tried different combinations of `--conventional-prerelease` but with no luck, if I can achieve what I'm describing above with the current feature set, then I'd be more than happy to use the existing API.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
Lerna-Lite is a fork of Lerna and that does not exist in Lerna. You can contribute the feature if you want, I just don't have time to implement this myself, that's not something I would ever use myself

**Comment by dreamorosi** [comment]
Thank you for the reply, I understand.
