### ISSUE TITLE
zero exit code on miss package

### ISSUE THREAD

**Issue by Naymi** [lerna-lite/lerna-lite#686]
### Describe the bug

![image](https://github.com/lerna-lite/lerna-lite/assets/21343944/66702946-7d2a-4eef-907e-e56a28b45081)

### Expectation

non zero exit code

### Reproduction

![image](https://github.com/lerna-lite/lerna-lite/assets/21343944/0fe4f0d0-d532-4380-9414-91ca0e528455)

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

  System:
    OS: Linux 5.19 Alpine Linux
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900
    Memory: 52.87 GB / 62.62 GB
    Container: Yes
    Shell: 1.36.1 - /bin/ash
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
fixed by #687
