### ISSUE TITLE
verion command not ignoring packages that are out of scope

### ISSUE THREAD

**Issue by z3dev** [lerna-lite/lerna-lite#731]
### Describe the bug

The JSCAD project contains some packages which will not be maintained / published. In order to control the packages in scope, the lerna.json has the packages section.

```
  "packages": [
    "packages/cli",
    "packages/core",
    "packages/io/*",
    "packages/modeling",
    "packages/web",
    "packages/utils/*"
  ]
```
However, it seems that the version command is trying to execute pnpm within a package which is not being maintained and not in scope (vtree), updating the lockfile version???

### Expectation

The version command should not run scripts for packages out of scope.

### Reproduction

```
lerna-lite ERR! Error: Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts
lerna-lite ERR! Scope: all 29 workspace projects
lerna-lite ERR!  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
lerna-lite ERR!  ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In packages/vtree: No matching version found for @jscad/stl-serializer@2.1.15 inside the workspace
lerna-lite ERR!     at makeError (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
lerna-lite ERR!     at handlePromise (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
lerna-lite ERR!     at runMicrotasks (<anonymous>)
lerna-lite ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lerna-lite ERR!     at async runInstallLockFileOnly (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/@lerna-lite+version@2.5.1_wh2y436zmbxhkdhpvoxjpwzluu/node_modules/@lerna-lite/version/dist/lib/update-lockfile-version.js:91:17)
lerna-lite ERR! Error: Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts
lerna-lite ERR! Scope: all 29 workspace projects
lerna-lite ERR!  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
lerna-lite ERR!  ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In packages/vtree: No matching version found for @jscad/stl-serializer@2.1.15 inside the workspace
lerna-lite ERR!     at makeError (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
lerna-lite ERR!     at handlePromise (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
lerna-lite ERR!     at runMicrotasks (<anonymous>)
lerna-lite ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lerna-lite ERR!     at async runInstallLockFileOnly (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/@lerna-lite+version@2.5.1_wh2y436zmbxhkdhpvoxjpwzluu/node_modules/@lerna-lite/version/dist/lib/update-lockfile-version.js:91:17)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts
Scope: all 29 workspace projects
 WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In packages/vtree: No matching version found for @jscad/stl-serializer@2.1.15 inside the workspace
    at makeError (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/execa@8.0.1/node_modules/execa/index.js:124:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runInstallLockFileOnly (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/@lerna-lite+version@2.5.1_wh2y436zmbxhkdhpvoxjpwzluu/node_modules/@lerna-lite/version/dist/lib/update-lockfile-version.js:91:17)
    at async VersionCommand.execute (file:///Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease/node_modules/.pnpm/@lerna-lite+version@2.5.1_wh2y436zmbxhkdhpvoxjpwzluu/node_modules/@lerna-lite/version/dist/version-command.js:204:9) {
  shortMessage: 'Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts',
  command: 'pnpm install --lockfile-only --ignore-scripts',
  escapedCommand: 'pnpm install --lockfile-only --ignore-scripts',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Scope: all 29 workspace projects\n' +
    ' WARN  `node_modules` is present. Lockfile only installation will make it out-of-date\n' +
    ' ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In packages/vtree: No matching version found for @jscad/stl-serializer@2.1.15 inside the workspace',
  stderr: '',
  cwd: '/Users/z3dev/dev/jscad/OpenJSCAD.org.v3-prerelease',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
 ELIFECYCLE  Command failed with exit code 1.
```

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "npmClient": "pnpm",
  "command": {
    "version": {
      "allowBranch": "v3-prerelease",
      "conventionalCommits": true,
      "exact": true,
      "message": "chore(release): publish",
      "syncWorkspaceLock": true
    }
  },
  "ignoreChanges": [
    "**/*.md"
  ],
  "packages": [
    "packages/cli",
    "packages/core",
    "packages/io/*",
    "packages/modeling",
    "packages/web",
    "packages/utils/*"
  ]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 4.07 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
    pnpm: 7.11.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 14.1.2
  npmPackages:
    @lerna-lite/changed: ^2.5.1 => 2.5.1 
    @lerna-lite/cli: ^2.5.1 => 2.5.1 
    @lerna-lite/publish: ^2.5.1 => 2.5.1 
    @lerna-lite/run: ^2.5.1 => 2.5.1 
    @lerna-lite/version: ^2.5.1 => 2.5.1 

```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by z3dev** [comment]
FYI, JSCAD has moved to PNPM with this release, so there's still a lot of new things to learn. However, we are kind of stuck on this issue. Any help would be appreciated.

**Comment by z3dev** [comment]
Here's the package.json of the out-of-sope package, vtree. It seems to have a dev dependency on the workspace packages. Maybe this is causing version to include it?

```
cat package.json 
{
  "name": "@jscad/vtree",
  "version": "2.0.26",
  "description": "Experimental Object Caching for JSCAD",
  "main": "index.js",
  "private": true,
  "scripts": {
    "output": "node user/index.js"
  },
  "contributors": [
    {
      "name": "Mark 'kaosat-dev' Moissette",
      "url": "https://github.com/kaosat-dev"
    }
  ],
  "keywords": [
    "openjscad",
    "jscad",
    "vtree",
    "cache"
  ],
  "license": "MIT",
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@jscad/array-utils": "workspace:2.1.4",
    "@jscad/modeling": "workspace:2.12.0",
    "object-hash": "2.0.3"
  },
  "devDependencies": {
    "@jscad/io-utils": "workspace:2.0.25",
    "@jscad/stl-serializer": "workspace:2.1.15",
    "decache": "^4.4.0",
    "just-diff": "^2.1.1",
    "serialize-to-js": "^3.0.2",
    "simple-diff": "^1.6.0"
  },
  "gitHead": "a90b9bad95a417661c619dc733e62c587dc71a4a"
}

```

**Comment by ghiscoding** [comment]
you didn't provide your `lerna.json`, make sure that your `npmClient` is set to `pnpm` and I don't quite understand your problem since you're asking about `lerna version` but you're showing issue with pnpm install. Lerna-Lite itself is using pnpm, you should check what settings are used to compare against your settings. I cannot help without a full repro and without understanding your issue. I would also suggest that you check the original Lerna [issues](https://github.com/lerna/lerna/issues) to see if there's anything similar to your problem.

**Comment by z3dev** [comment]
I'll update the issue but if you look at the log, it says...

`@lerna-lite+version@2.5.1_wh2y436zmbxhkdhpvoxjpwzluu/node_modules/@lerna-lite/version/dist/lib/update-lockfile-version.js:91:17)`

And, it's calling PNPM install, so it's obviously pnpm is configured.

Why does Lerna call pnpm install at this point? It's failing during a publish. It doesn't fail during a dry run.

I would guess that pnpm does understand the packages of Lerna, so is there a way to make pnpm ignore certain packages?

**Comment by z3dev** [comment]
If you ask me... it seems that `--prod` should be added to the pnpm command line arguments. the installation of the STL packages should be ignored as that is a dev dependency.

**Comment by ghiscoding** [comment]
> `@lerna-lite+version@2.5.1_wh2y436zmbxhkdhpvoxjpwzluu/node_modules/@lerna-lite/version/dist/lib/update-lockfile-version.js:91:17)`
> 
> And, it's calling PNPM install, so obviously pnpm is configured.

There is only 1 instance where it could run an install and that is if you use the version flag [`syncWorkspaceLock`](https://github.com/lerna-lite/lerna-lite/tree/main/packages/version#--sync-workspace-lock) which will run an install **with lock file** as per this code with pnpm and that is not a full install, using these options is a simple way to update the lock file only (node_modules will never be updated) as per pnpm docs [--lockfile-only](https://pnpm.io/cli/install#--lockfile-only)

> When used, only updates `pnpm-lock.yaml` and `package.json`. Nothing gets written to the `node_modules` directory.

https://github.com/lerna-lite/lerna-lite/blob/main/packages/version/src/lib/update-lockfile-version.ts#L137-L145

if you look at the code, you'll see which arguments it calls and the argument is `npmClientArgs` and you can use that to add any pnpm argument you want (like `--prod` if that is your wish)
