### ISSUE TITLE
lerna version unable to `git push` back to repo

### ISSUE THREAD

**Issue by kpotschi** [lerna-lite/lerna-lite#790]
### Describe the bug

lerna version unable to `git push` back to repo.

### Expectation

ideally i was hoping lerna-lite version would use the provided `GL_TOKEN` to try and access our company's gitlab instance, but that doesn't seem to be the case.

### Reproduction

current gitlab ci/cd script:

```
script:
    - npx lerna run build
    - git checkout $CI_COMMIT_BRANCH
    - git fetch
    - git rebase
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_LOGIN"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - npx lerna version --conventional-commits --yes
 ```

output:
```
lerna-lite ERR! Error: Command failed with exit code 128: git push --follow-tags --no-verify --atomic origin main
lerna-lite ERR! remote: You are not allowed to upload code.
lerna-lite ERR! fatal: unable to access 'xxx': The requested URL returned error: 403
```
`GL_API_URL` and `GL_TOKEN` are provided as stated in the [readme](https://www.npmjs.com/package/@lerna-lite/version#gitlab-auth-token)

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
	"$schema": "node_modules/@lerna-lite/cli/schemas/lerna-schema.json",
	"npmClient": "yarn",
	"version": "1.0.0",
	"command": {
		"version": {
			"allowBranch": "main"
		}
	}
}

```
</p></details>

### Environment Info

  System:
    OS: Linux 6.2 Alpine Linux
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    Memory: 13.31 GB / 15.61 GB
    Container: Yes
    Shell: 1.36.1 - /bin/ash
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 3.6.4 - /builds/gameland/ploom-extensions-sdk/node_modules/.bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  npmPackages:
    @lerna-lite/cli: ^3.1.0 => 3.1.0 
    @lerna-lite/core: ^3.1.0 => 3.1.0 
    @lerna-lite/publish: ^3.1.0 => 3.1.0 
    @lerna-lite/run: ^3.1.0 => 3.1.0 
    @lerna-lite/version: ^3.1.0 => 3.1.0 

### Used Package Manager

yarn >= 2.x

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Hello, I don't use GitLab and this code was created by the original author and I have never touched the GitLab logic. However I don't see the `GL_TOKEN` being used anywhere in your scripts, I'm pretty sure that the token has to be part of your scripts/workflow somewhere and I don't think it can guess the token without telling it how to use it. For example, this article [Lerna and Turborepo with Gitlab CI/CD](https://www.delightfulengineering.com/blog/lerna-turbo-gitlab) does include the `GL_TOKEN` in their scripts... I'm afraid that I cannot help much more than that

**Comment by kpotschi** [comment]
`GL_TOKEN` would be provided through the GitLab pipeline and made available as a `process.env` variable. 

here's a workaround to set the token manually, in case anyone stumbles upon this as well:

in the ci/cd script

```
    - git remote set-url origin https://[token name]:[gitlab token ci var]@[git url]
```

**Comment by ghiscoding** [comment]
so did you get it working? I'm afraid I cannot help at all with your issue but in GitHub Actions we have to provide the token through `env`, for example this is what I use in Lerna-Lite itself to release


https://github.com/lerna-lite/lerna-lite/blob/cbea60fdbcdb51d449fd0dd81ff5214e71587a8d/.github/workflows/publish-npm-latest.yml#L68-L73
