### ISSUE TITLE
Commit url pattern for azure (commitUrlFormat)

### ISSUE THREAD

**Issue by MichaelGitArt** [lerna-lite/lerna-lite#792]
### Describe the bug

Currently, when we use --conventional-commits, we have a changelog with commit links. But it takes the remote origin URL and adds '/commits/COMMIT_ID'. But when we use Azure, it doesn't work. There we have more specific links to commit. So we receive 404.

Would be nice to add the option commitUrlFormat. Like here: https://github.com/lerna/lerna/issues/2526#issuecomment-661286054

### Reproduction

Any project where you need to specify commit link

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

Any lerna-lite/version using --conventional-commits

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
any specific conventional changelog config you want to pass can be provided in `version.changelogPreset` as pointed out in the next post of the same link you referenced, also don't forget to add a name when you use that type of config

**Comment by MichaelGitArt** [comment]
@ghiscoding Thanks a lot! 

It's not related to the "lerna-lite", but maybe you know. How to use the default angular preset, but with specified  `commitUrlFormat`? The code below doesn't work.

```
 "changelogPreset": {
    "name": "angular",
    "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/someurl/{{hash}}"
  },
```

**Comment by ghiscoding** [comment]
I don't know, I only use the regular changelog preset, you should search in the Lerna repo or on the internet. The main reason I created this repo was to update all the dependencies and some other reasons that I wrote about in the homepage. There's a lot of things that I do not know about and this one of them. Nonetheless, I think this is all related to configurations not the library itself, since this is not an issue, I will close this one
