### ISSUE TITLE
`removePackageFields` actually modifies my package.json

### ISSUE THREAD

**Issue by farfromrefug** [lerna-lite/lerna-lite#813]
### Describe the bug

i tried to use `removePackageFields` with `scripts` to not publish my `scripts` in npm
However i realized it actually removed `scripts` from all my package.json files (one per package) which was really bad as then my packages were not building anymore and i even managed to publish empty versions of all my packages.

The weird thing is i am sure i have been using it in other repos (i use it in like 30 repos) without it actually modifying my package.json

### Expectation

`scripts` not in published `package.json` but still present in my repo

### Reproduction

happened on this repo https://github.com/nativescript-community/ui-material-components by running `npm run publish`

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
    "version": "4.3.29",
    "$schema": "node_modules/@lerna-lite/cli/schemas/lerna-schema.json",
    "packages": [
        "packages/*"
    ],
    "npmClient": "yarn",
    "useWorkspaces": true,
    "command": {
        "publish": {
            "cleanupTempFiles": true,
            "removePackageFields": [
                "devDependencies",
                "scripts"
            ]
        }
    },
    "npmClientArgs": [
        "--no-package-lock"
    ],
    "commitHooks": false,
    "createRelease": "github",
    "conventionalCommits": true,
    "private": false,
    "message": "chore(release): publish new version %v",
    "changelogPreset": "conventional-changelog-conventionalcommits",
    "ignoreChanges": [
        "**/__fixtures__/**",
        "**/__tests__/**",
        "**/*.md"
    ]
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

System:
    OS: Linux 6.6 Pop!_OS 22.04 LTS
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 23.77 GB / 62.64 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 4.0.1 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm

### Used Package Manager

yarn >= 2.x

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
> i tried to use `removePackageFields` with `scripts` to not publish my `scripts` in npm
> However i realized it actually removed `scripts` from all my package.json files (one per package) which was really bad as then my packages were not building anymore and i even managed to publish empty versions of all my packages.

It removes the field(s) just before publishing by modifying `package.json` temporarily (there's no cache involved) in **all** packages, it's exactly the same process as replacing the `workspace:` protocol. Technically speaking, at that point in time your library should have already been built. There was another similar issue #637 opened which was related to lifecycle scripts (`prepack`, `postpack`, ...) and the fix for that issue was to simply leave these lifecycle scripts in place when publishing, so you could use those if that helps. You should try with `--dry-run` mode, it modifies the files and you'll see the changes in Git of all your files including the `package.json`, if it doesn't fulfill your request then I suggest you use a different approach because like I said there's no cache involved and probably never will be since that would require way too much effort 

I personally use this `removePackageFields` in all my repos to remove `scripts` and `devDependencies` and never had any problems with it but again I would strongly suggest you try the `dry-run` mode to see what the output will be

**Comment by farfromrefug** [comment]
@ghiscoding thanks for the explanation. So if i understand correctly you delete the fields and modify "my" file locally. Then revert it after the publish?
If so then i guess what i see can happen if something fails between the modification and the restore?
I know i did break the process with a wrong npm totp token.
Could that create the issue? 

It broke my build system because the change was commited and thus on the next run of publish i did not have any scripts anymore

**Comment by ghiscoding** [comment]
It's supposed to only change the file just before the package is packed as a tarball, it's supposed to be transparent to the user and is not supposed to push the change to git (it never does on my side). The only exception is a lifecycle script and when that happens, it can interfere with the process but again these changes should never be pushed to git. For example when we use the `workspace:` protocol, it replaces the `workspace:*` with the real version then packs it as a tarball and then publishes it to npm, but it never commits any change to the `workspace:*`. It shouldn't break anyone's process except when it's a lifecycle script (those are kept in the tarball and published to npm as well).

Again I would suggest you try the `--dry-run` mode to see the output, which it doesn't seem that you've tried yet

**Comment by ghiscoding** [comment]
Bonjour, 
I made a change in PR #817 this will hopefully fix your issue even though I'm not 100% that it will. I think your use case is very particular, for example each of your `package.json` include a `gitHead` property but that shouldn't be part of your package at all, this property is a temporary property that is only added in the package just before the npm publish (the process is exactly the same as replacing all the versions with `workspace:*` protocol and removing the `scripts` and `devDependencies`), once the publish is done then these properties are reversed to their original values so why are these temp values actually included in your original package.json? It seems a little weird to me. So anyway, hope for the best. Cheers
