### ISSUE TITLE
Cannot spot the changed packages correctly when a custom version provided as command parameter

### ISSUE THREAD

**Issue by afshin-hoseini** [lerna-lite/lerna-lite#845]
### Describe the bug

Lerna cannot detect changed packages when publishing with a custom version, provided as `publish` command's parameter. But can figure out when providing the same custom version using prompt.

### Expectation

It should spot the changes the same way in either ways.

### Reproduction

- I got two packages ( **pkg-a** and **pkg-b** ), where **pkg-b** depends on **pkg-a**.
- I published both of them with `10.3.0-ticket-1234-1` as version.
- I apply some changes on **pkg-b** and commit it.
- When I run `npx lerna publish` and then select the `custom version` option from the prompt, and input the next version as `10.3.0-ticket-1234-2`, it identifies **pkg-b** as the only changed package, **_which is correct_**.
- **_However_**, if I provide the version along with the command like `npx lerna publish 10.3.0-ticket-1234-2`, it cannot identify the changed packages correctly and wanna publish both `pkg-a` and `pkg-b`.

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "10.3.0-ticket-1234-1",
  "packages": [
    "packages/*"
  ]
}
```
</p></details>

### Environment Info

```
  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.20 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Utilities:
    Git: 2.39.3 - /usr/bin/git
  npmPackages:
    lerna: 8.1.2 => 8.1.2 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I think that is the default behavior of Lerna and it was added by the original author of Lerna

When providing a version, it's defined as a global version and I'm assuming it's for probably all packages (so I'm guessing it's falling under either line 438 or 441) and it seems to be using `semver.inc` for all packages. However when using prompt, as you mentioned, it will skip unchanged packages. So when comes the time to publish, the global version has more packages to publish. These are all just assumptions, you should troubleshoot it yourself.

https://github.com/lerna-lite/lerna-lite/blob/291bf01c5e0b49e70733c8abb17e2bb8141d5cbe/packages/version/src/version-command.ts#L437-L470
