### ISSUE TITLE
--sync-workspace-lock issue

### ISSUE THREAD

**Issue by achille1789** [lerna-lite/lerna-lite#877]
### Describe the bug

A short overview first: 
I have a"postinstall" script that runs "husky install" ([Husky](https://www.npmjs.com/package/husky) is npm package).
Using Husky, I run a script on the git "pre-commit" hook that checks the name of the branch and fails the commit in case the branch name is not formatted as expected (branch "main" fails the script).
When I merge a branch on "main", the pipeline:
1. sets this env vars: HUSKY=0
2. installs the dependencies but because of the above env var, Husky is not initialised
3. runs "lerna version"
4. lerna bumps the version, updates the package-lock.json, commits and pushes the tag

Everything works as expected as long as I don't set `syncWorkspaceLock: true` in lerna.json (I use npm).
Setting the flag to true, Lerna fails to commit because the "pre-commit" hook is triggered and the script throws an error because the branch name is "main".

### Expectation

As suggested by the docs, I should use syncWorkspaceLock: true and Lerna should be able to commit.

### Reproduction

Should be possible to reproduce the issue following my bug description.

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/@lerna-lite/cli/schemas/lerna-schema.json",
  "version": "independent",
  "command": {
    "version": {
      "allowBranch": [
        "main"
      ],
      "message": "chore(release): [ci skip] version bump",
      "conventionalCommits": true,
      "private": false
    }
  },
  "yes": true,
  "changelogPreset": "./changelog-preset.config.js",
  "ignoreChanges": [
    "**/Tests/**"
  ],
  "useWorkspaces": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 258.52 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Browsers:
    Chrome: 125.0.6422.176
    Safari: 17.5
  npmPackages:
    @lerna-lite/cli: ^3.5.1 => 3.5.1 
    @lerna-lite/run: ^3.5.1 => 3.5.1 
    @lerna-lite/version: ^3.5.2 => 3.5.2 

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I don't use Husky and don't have much knowledge about it, all I know is that below is what the npm lock file update runs. This flag was created to sync the lock file and that's all it should do. It does accept extra npm arguments if that helps.

https://github.com/lerna-lite/lerna-lite/blob/3204e062cb42578fddd5e8314b0c73d230d2fac8/packages/version/src/lib/update-lockfile-version.ts#L161-L181

Looking at the Version command, the sync seems to happen before the `version` and `postversion` lifecycles. 

https://github.com/lerna-lite/lerna-lite/blob/3204e062cb42578fddd5e8314b0c73d230d2fac8/packages/version/src/version-command.ts#L782-L793

Then the `version` lifecycle is at line 838 and the `postversion` lifecycle is at line 860.

So I don't know what your problem is since I don't use that kind of scripts on my side and I can't provide much more info. The oly suggestion I could do is to look at the available version [Lifecycle Scripts](https://github.com/lerna-lite/lerna-lite/tree/main/packages/version#lifecycle-scripts) and maybe use a different one if that helps, otherwise I have no idea.

**Comment by achille1789** [comment]
Hi @ghiscoding many thanks for your quick and detailed response!

I investigated a little bit and basically the problem is that `npm install --package-lock-only` runs all the npm hooks, so setting "syncWorkspaceLock: true" was causing husky to be initialised, because HUSKY env var was already out of scope when this command run.
Leaving "syncWorkspaceLock: false" doesn't run `npm install --package-lock-only` so there is no problem.

I bypassed the issue moving HUSKY env var in the parent scope and now even setting "syncWorkspaceLock: true", when Lerna runs `npm install --package-lock-only` the HUSKY var is set and Husky is not initialised.

Anyway, looking at the original Lerna code:
https://github.com/lerna/lerna/blob/7bd983510110d00d9c3db94fb99f74773ab75d40/libs/commands/version/src/index.ts?#L811-L827

it is running `npm install --package-lock-only --ignore-scripts` that prevents to run the NPM hooks. So I don't know if it worths to do the same, just to avoid any issue in future when people migrate from Lerna to Lerna-lite

**Comment by ghiscoding** [comment]
> Anyway, looking at the original Lerna code: https://github.com/lerna/lerna/blob/7bd983510110d00d9c3db94fb99f74773ab75d40/libs/commands/version/src/index.ts?#L811-L827
> 
> it is running `npm install --package-lock-only --ignore-scripts` that prevents to run the NPM hooks. So I don't know if it worths to do the same, just to avoid any issue in future when people migrate from Lerna to Lerna-lite

hmm there is actually a CLI option `runScriptsOnLockfileUpdate` to pass for the command to ignore script, I guess we could add the same option in here too

**Comment by achille1789** [comment]
> Side note and as mentioned above you could also add the ignore script yourself via the `npmClientArgs` in the Lerna version command, so I guess something like this should work (untested), you can refer to the docs [--npm-client-args](https://github.com/lerna-lite/lerna-lite/tree/3204e062cb42578fddd5e8314b0c73d230d2fac8/packages/version#--npm-client-args)
> 
> ```ts
> {
>   "command": {
>     "version": {
>       "npmClientArgs": ["--ignore-scripts"]
>     }
> }
> ```
> 
> that is until I have time to add the other skip script run option. or you could also contribute the missing option 😉

Hi @ghiscoding, as I said, I already solved my problem but I will keep in mind this as future reference!
Thanks

**Comment by ghiscoding** [comment]
latest release [v3.6.0](https://github.com/lerna-lite/lerna-lite/releases/tag/v3.6.0) will no longer run scripts when npm install runs, the behavior is now the same as Lerna and if you want to run the scripts then the new option `runScriptsOnLockfileUpdate` will let you do that
