### ISSUE TITLE
'version' command | Unknown argument "skipBumpOnlyReleases"

### ISSUE THREAD

**Issue by SchulteMarkus** [lerna-lite/lerna-lite#924]
### Describe the bug

When using lerna-lite version argument '--skip-bump-only-releases' https://github.com/lerna-lite/lerna-lite/blob/main/packages/version/README.md#--skip-bump-only-releases, lerna-lite version does not execute, but fails with:

    ERR! lerna-lite Unknown arguments: skip-bump-only-releases, skipBumpOnlyReleases

Using '--skip-bump-only-release' works fine, though.

Related issue #703 => pr #721
    

### Expectation

lerna-lite version executes fine with '--skip-bump-only-releases'.

### Reproduction

    $ npx -y -p conventional-changelog-conventionalcommits@7 -p @lerna-lite/cli@3.9.0 -p @lerna-lite/version@3.9.0 \
      lerna version --yes --skip-bump-only-releases --dry-run

    ERR! lerna-lite Unknown arguments: skip-bump-only-releases, skipBumpOnlyReleases

### Environment Info

$ npm -v
10.8.1

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
oh yeah it was originally singular and I rename the option as plural everywhere else but missed the CLI one. Would you like to create a PR to fix it? 

https://github.com/lerna-lite/lerna-lite/blob/8d028847e8237a9b8ab94e36b23050aae219629c/packages/cli/src/cli-commands/cli-version-commands.ts#L284-L287

**Comment by SchulteMarkus** [comment]
I'm afraid my TypeScript knowledge is insufficient to make good changes in such an extensive project.

**Comment by ghiscoding** [comment]
it's really just a typo and it is just missing a single character, we can even fix it by using GitHub directly. There's no actual tests for the CLI command itself which is why it wasn't caught earlier (the command has unit tests but not directly from the CLI).
