### ISSUE TITLE
lerna.json useWorkspaces is not allowed

### ISSUE THREAD

**Issue by achille1789** [lerna-lite/lerna-lite#930]
### Describe the bug

Hi, I am not sure if it is an actual bug but I don't find any note about it.
My lerna.json has the property: ```"useWorkspaces": true```
The schema was allowing the property with v3.8.0 but with v3.9.0 (and 3.9.1 too), my editor complains that that property is not longer allowed. 

### Expectation

Probably the same behaviour as in v3.8.0

### Reproduction

lerna.json:
```json
{
  "$schema": "node_modules/@lerna-lite/cli/schemas/lerna-schema.json",
  "version": "independent",
  "command": {
    "version": {
      "allowBranch": [
        "main"
      ],
      "message": "chore(release): [ci skip] version bump",
      "conventionalCommits": true,
      "private": false,
      "syncWorkspaceLock": true
    }
  },
  "yes": true,
  "changelogPreset": "./changelog-preset.config.js",
  "useWorkspaces": true,
  "npmClient": "npm",
  "ignoreChanges": [
    "**/unit/**"
  ]
}
```

all good with version 3.8.0
useWorkspaces not allowed with version 3.9.0

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 139.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.6
  npmPackages:
    @lerna-lite/cli: 3.9.0 => 3.9.0 
    @lerna-lite/run: 3.9.0 => 3.9.0 
    @lerna-lite/version: 3.9.0 => 3.9.0 

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
hmm I'm not sure if recent PR #921 could have an impact? It's a PR that I replicated from Lerna's original repo. If you spot the error feel free to contribute a fix. In the meantime, a schema error won't stop you from using the project, it's not like TypeScript but like an intellisense helper
