### ISSUE TITLE
Skip bump only releases in fixed mode, too

### ISSUE THREAD

**Issue by SchulteMarkus** [lerna-lite/lerna-lite#933]
### Clear and concise description of the problem

There is the `version` option [--skip-bump-only-releases](https://github.com/lerna-lite/lerna-lite/tree/main/packages/version#--skip-bump-only-releases)

> this option is only useful and can only be used with independent mode. Also please note that each changelogs are still going to be updated with the "version bump only" text and only the releases will be skipped.

From my point of view, the use of this option in [fixed mode](https://lerna.js.org/docs/features/version-and-publish#fixedlocked-mode-default) would also be desirable, as ‘version bump only’ releases can also occur here.

### Suggested solution

[--skip-bump-only-releases](https://github.com/lerna-lite/lerna-lite/tree/main/packages/version#--skip-bump-only-releases) supports fixed mode, too.

### Alternative

Using `version --dry-run` and shell-scripting, "version bump only" can be avoided https://stackoverflow.com/questions/78990282/how-to-avoid-version-bump-only-releases-in-fixed-mode

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
I think you might have misunderstood what this option really does. It skips GitHub [Releases](https://github.com/lerna-lite/lerna-lite/releases) in the UI on the GitHub page only. It will still bump and publish the package version and update the changelogs, it's only the GitHub (UI) Release that is being skipped. 

When you're using fixed mode, you are ready to publish and create a GitHub Release in the UI. You should never have a bump only release in the UI when using fixed mode (you could get some in the changelogs but again this option **does not** skip those)

**Comment by SchulteMarkus** [comment]
You're right, I have been thinking about not publishing (to NPM registry) in case of a "version bump only". If you want, feel free to close this issue.
But, on the other side, I think `--skip-bump-only-releases supports fixed mode, too.` remains kind of valid.
